## Load data and packages

In [1]:
# import basic packages

import numpy as np
import os
import time
from dask import dataframe as dd
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import vitaldb
import csv
from datetime import datetime, time as datetime_time, timedelta
import glob
import sys
import sklearn.neighbors._base
import vitaldb
import itertools

In [2]:
# Import relevant libraries
import torch
import torch.nn as nn

import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import math
import tensorflow as tf
%matplotlib inline
from sklearn.metrics import auc, classification_report, confusion_matrix, accuracy_score, roc_curve, roc_auc_score, f1_score, precision_recall_curve
from torch.autograd import Variable

In [3]:
# Option to fully display columns and rows
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 300)

In [4]:
# function to get root directory
def getRootDir():
    """
    Get root folder directory
    :return: root folder directory
    :rtype: path
    """
    rootdir = os.path.abspath(os.curdir)

    return rootdir
rootdir = getRootDir()
rootdir

'/Users/tselanna/Desktop/Code'

In [5]:
# Import dataset from hard drive
df = glob.glob(os.path.join(
        rootdir, 'TOSHIBA_HDD/2022_07_15T18_01_25_ANALYSIS_DF_44var.csv'))
df = pd.read_csv(df[0], dtype={"Solar8000/BT": float})

In [6]:
x = df.caseid[df['Solar8000/NIBP_MBP'].le(65)].unique()
print(x)

[  30   50   57   62  109  116  133  135  166  192  194  196  220  230
  238  305  320  323  351  465  476  483  487  489  517  525  551  569
  591  613  618  651  664  707  739  780  782  799  801  820  851  865
  873  898  924  965  966  975 1021 1026 1081 1104 1134 1137 1149 1155
 1175 1189 1207 1214 1236 1255 1258 1259 1308 1311 1315 1378 1401 1421
 1422 1435 1450 1453 1457 1461 1467 1476 1483 1492 1499 1502 1508 1510
 1526 1567 1655 1671 1709 1718 1731 1741 1742 1767 1788 1792 1796 1803
 1813 1815 1819 1824 1859 1873 1879 1880 1923 1934 1977 2003 2026 2037
 2038 2045 2054 2068 2078 2094 2100 2104 2105 2109 2124 2126 2190 2215
 2220 2229 2235 2247 2248 2308 2316 2343 2362 2363 2378 2389 2407 2430
 2431 2456 2462 2470 2475 2491 2496 2506 2517 2531 2540 2551 2565 2567
 2570 2580 2588 2617 2634 2754 2767 2773 2779 2784 2792 2805 2813 2829
 2842 2881 2885 2886 2923 2928 2934 2936 2937 2953 2957 2989 3022 3029
 3039 3052 3053 3062 3155 3163 3170 3183 3195 3213 3224 3234 3253 3265
 3283 3285 3302 3310 3326 3343 3382 3397 3413 3423 3477 3480 3494 3512
 3531 3532 3546 3547 3552 3557 3562 3597 3609 3624 3638 3639 3670 3678
 3684 3695 3703 3714 3724 3732 3735 3764 3779 3780 3788 3801 3808 3851
 3874 3893 3918 3920 3933 3943 3961 4007 4075 4087 4110 4154 4158 4160
 4229 4248 4257 4288 4303 4326 4334 4355 4363 4366 4383 4395 4451 4456
 4469 4482 4491 4517 4531 4608 4617 4646 4657 4670 4688 4691 4701 4709
 4735 4783 4829 4840 4848 4850 4888 4897 4925 4943 4962 4970 4972 5011
 5017 5020 5032 5041 5086 5087 5115 5130 5139 5167 5196 5211 5229 5249
 5252 5263 5279 5284 5293 5297 5318 5335 5345 5361 5387 5400 5465 5494
 5506 5516 5540 5555 5568 5570 5582 5601 5631 5639 5644 5672 5700 5716
 5731 5737 5741 5742 5756 5764 5786 5798 5821 5828 5879 5881 5900 5913
 5949 5960 6001 6023 6036 6059 6112 6118 6137 6146 6181 6225 6226 6232
 6241 6263 6265 6272 6294 6317 6321 6325 6340 6352 6356 6358 6360 6385]

In [7]:
len(x)

378

In [11]:
y = np.setdiff1d(ids, x)
print(len(y))
print(y)

226
[   1   21   88  124  140  207  211  224  239  243  269  313  329  384
  446  459  498  501  503  534  535  548  581  600  606  608  612  616
  653  681  687  696  755  808  830  832  859  927  930  937  939  958
  978  982 1082 1086 1088 1130 1156 1167 1200 1201 1210 1232 1244 1316
 1359 1367 1379 1381 1405 1434 1479 1494 1562 1568 1591 1625 1666 1694
 1721 1743 1764 1766 1826 1854 1928 1965 1993 2082 2107 2108 2201 2242
 2255 2265 2278 2287 2302 2306 2345 2346 2351 2371 2372 2373 2448 2501
 2549 2559 2624 2630 2649 2693 2707 2712 2800 2820 2825 2834 2863 2921
 2930 3048 3059 3079 3110 3161 3180 3189 3227 3250 3254 3314 3356 3358
 3398 3401 3427 3431 3449 3496 3535 3604 3620 3621 3623 3656 3677 3704
 3713 3728 3754 3761 3786 3823 3914 3924 3982 3992 4010 4028 4057 4097
 4114 4121 4186 4225 4249 4269 4354 4375 4378 4432 4437 4458 4563 4607
 4626 4627 4686 4711 4729 4759 4770 4773 4775 4825 4826 4874 4898 4909
 4912 4948 5013 5046 5050 5068 5128 5140 5187 5198 5206 5215 5221 5295
 5378 5395 5402 5423 5469 5509 5523 5566 5596 5600 5627 5658 5734 5834
 5888 5911 5927 5935 5968 5984 6045 6116 6123 6133 6210 6214 6218 6231
 6253 6316]

In [8]:
ids = [1,   21,   30,   50,   57,   62,   88,  109,  116,  124,  133,
        135,  140,  166,  192,  194,  196,  207,  211,  220,  224,  230,
        238,  239,  243,  269,  305,  313,  320,  323,  329,  351,  384,
        446,  459,  465,  476,  483,  487,  489,  498,  501,  503,  517,
        525,  534,  535,  548,  551,  569,  581,  591,  600,  606,  608,
        612,  613,  616,  618,  651,  653,  664,  681,  687,  696,  707,
        739,  755,  780,  782,  799,  801,  808,  820,  830,  832,  851,
        859,  865,  873,  898,  924,  927,  930,  937,  939,  958,  965,
        966,  975,  978,  982, 1021, 1026, 1081, 1082, 1086, 1088, 1104,
       1130, 1134, 1137, 1149, 1155, 1156, 1167, 1175, 1189, 1200, 1201,
       1207, 1210, 1214, 1232, 1236, 1244, 1255, 1258, 1259, 1308, 1311,
       1315, 1316, 1359, 1367, 1378, 1379, 1381, 1401, 1405, 1421, 1422,
       1434, 1435, 1450, 1453, 1457, 1461, 1467, 1476, 1479, 1483, 1492,
       1494, 1499, 1502, 1508, 1510, 1526, 1562, 1567, 1568, 1591, 1625,
       1655, 1666, 1671, 1694, 1709, 1718, 1721, 1731, 1741, 1742, 1743,
       1764, 1766, 1767, 1788, 1792, 1796, 1803, 1813, 1815, 1819, 1824,
       1826, 1854, 1859, 1873, 1879, 1880, 1923, 1928, 1934, 1965, 1977,
       1993, 2003, 2026, 2037, 2038, 2045, 2054, 2068, 2078, 2082, 2094,
       2100, 2104, 2105, 2107, 2108, 2109, 2124, 2126, 2190, 2201, 2215,
       2220, 2229, 2235, 2242, 2247, 2248, 2255, 2265, 2278, 2287, 2302,
       2306, 2308, 2316, 2343, 2345, 2346, 2351, 2362, 2363, 2371, 2372,
       2373, 2378, 2389, 2407, 2430, 2431, 2448, 2456, 2462, 2470, 2475,
       2491, 2496, 2501, 2506, 2517, 2531, 2540, 2549, 2551, 2559, 2565,
       2567, 2570, 2580, 2588, 2617, 2624, 2630, 2634, 2649, 2693, 2707,
       2712, 2754, 2767, 2773, 2779, 2784, 2792, 2800, 2805, 2813, 2820,
       2825, 2829, 2834, 2842, 2863, 2881, 2885, 2886, 2921, 2923, 2928,
       2930, 2934, 2936, 2937, 2953, 2957, 2989, 3022, 3029, 3039, 3048,
       3052, 3053, 3059, 3062, 3079, 3110, 3155, 3161, 3163, 3170, 3180,
       3183, 3189, 3195, 3213, 3224, 3227, 3234, 3250, 3253, 3254, 3265,
       3283, 3285, 3302, 3310, 3314, 3326, 3343, 3356, 3358, 3382, 3397,
       3398, 3401, 3413, 3423, 3427, 3431, 3449, 3477, 3480, 3494, 3496,
       3512, 3531, 3532, 3535, 3546, 3547, 3552, 3557, 3562, 3597, 3604,
       3609, 3620, 3621, 3623, 3624, 3638, 3639, 3656, 3670, 3677, 3678,
       3684, 3695, 3703, 3704, 3713, 3714, 3724, 3728, 3732, 3735, 3754,
       3761, 3764, 3779, 3780, 3786, 3788, 3801, 3808, 3823, 3851, 3874,
       3893, 3914, 3918, 3920, 3924, 3933, 3943, 3961, 3982, 3992, 4007,
       4010, 4028, 4057, 4075, 4087, 4097, 4110, 4114, 4121, 4154, 4158,
       4160, 4186, 4225, 4229, 4248, 4249, 4257, 4269, 4288, 4303, 4326,
       4334, 4354, 4355, 4363, 4366, 4375, 4378, 4383, 4395, 4432, 4437,
       4451, 4456, 4458, 4469, 4482, 4491, 4517, 4531, 4563, 4607, 4608,
       4617, 4626, 4627, 4646, 4657, 4670, 4686, 4688, 4691, 4701, 4709,
       4711, 4729, 4735, 4759, 4770, 4773, 4775, 4783, 4825, 4826, 4829,
       4840, 4848, 4850, 4874, 4888, 4897, 4898, 4909, 4912, 4925, 4943,
       4948, 4962, 4970, 4972, 5011, 5013, 5017, 5020, 5032, 5041, 5046,
       5050, 5068, 5086, 5087, 5115, 5128, 5130, 5139, 5140, 5167, 5187,
       5196, 5198, 5206, 5211, 5215, 5221, 5229, 5249, 5252, 5263, 5279,
       5284, 5293, 5295, 5297, 5318, 5335, 5345, 5361, 5378, 5387, 5395,
       5400, 5402, 5423, 5465, 5469, 5494, 5506, 5509, 5516, 5523, 5540,
       5555, 5566, 5568, 5570, 5582, 5596, 5600, 5601, 5627, 5631, 5639,
       5644, 5658, 5672, 5700, 5716, 5731, 5734, 5737, 5741, 5742, 5756,
       5764, 5786, 5798, 5821, 5828, 5834, 5879, 5881, 5888, 5900, 5911,
       5913, 5927, 5935, 5949, 5960, 5968, 5984, 6001, 6023, 6036, 6045,
       6059, 6112, 6116, 6118, 6123, 6133, 6137, 6146, 6181, 6210, 6214,
       6218, 6225, 6226, 6231, 6232, 6241, 6253, 6263, 6265, 6272, 6294,
       6316, 6317, 6321, 6325, 6340, 6352, 6356, 6358, 6360, 6385]

In [12]:
import scipy.stats as stat
from tableone import TableOne

In [19]:
df['label'] = np.where(df['caseid'].isin(x), 'IOH', 'Normal')

In [21]:
df = df.drop(['lbl'], axis=1)

In [22]:
df

,caseid,age,height,weight,bmi,asa,preop_htn,preop_dm,preop_hb,preop_plt,preop_pt,preop_aptt,preop_na,preop_k,preop_gluc,preop_alb,preop_ast,preop_alt,preop_bun,preop_cr,intraop_ebl,intraop_uo,intraop_crystalloid,intraop_ppf,intraop_ftn,intraop_rocu,intraop_eph,Primus/MAC,Primus/PEEP_MBAR,Solar8000/BT,Solar8000/ETCO2,Solar8000/FEO2,Solar8000/FIO2,Solar8000/HR,Solar8000/INCO2,Solar8000/NIBP_DBP,Solar8000/NIBP_MBP,Solar8000/NIBP_SBP,Solar8000/PLETH_HR,Solar8000/PLETH_SPO2,Solar8000/RR_CO2,Solar8000/VENT_MAWP,Solar8000/VENT_RR,seconds,label
0,1,77.0,160.2,67.5,26.3,2.0,1,0,14.1,189.0,94.0,33.2,141.0,3.1,134.0,4.3,18.0,16.0,10.0,0.82,-1.0,300.0,350.0,120,100,70,10,0.0,1.0,21.100000,30.0,89.0,95.0,84.0,1.0,84.0,100.0,150.0,85.0,97.0,5.0,0.0,18.0,96,Normal
1,1,77.0,160.2,67.5,26.3,2.0,1,0,14.1,189.0,94.0,33.2,141.0,3.1,134.0,4.3,18.0,16.0,10.0,0.82,-1.0,300.0,350.0,120,100,70,10,0.0,1.0,21.100000,30.0,89.0,95.0,84.0,1.0,84.0,100.0,150.0,84.0,97.0,5.0,0.0,18.0,98,Normal
2,1,77.0,160.2,67.5,26.3,2.0,1,0,14.1,189.0,94.0,33.2,141.0,3.1,134.0,4.3,18.0,16.0,10.0,0.82,-1.0,300.0,350.0,120,100,70,10,0.0,1.0,21.000000,30.0,89.0,95.0,84.0,1.0,84.0,100.0,150.0,85.0,97.0,5.0,0.0,18.0,100,Normal
3,1,77.0,160.2,67.5,26.3,2.0,1,0,14.1,189.0,94.0,33.2,141.0,3.1,134.0,4.3,18.0,16.0,10.0,0.82,-1.0,300.0,350.0,120,100,70,10,0.0,1.0,21.000000,30.0,89.0,95.0,85.0,1.0,84.0,100.0,150.0,85.0,97.0,5.0,0.0,18.0,102,Normal
4,1,77.0,160.2,67.5,26.3,2.0,1,0,14.1,189.0,94.0,33.2,141.0,3.1,134.0,4.3,18.0,16.0,10.0,0.82,-1.0,300.0,350.0,120,100,70,10,0.0,1.0,21.000000,30.0,89.0,95.0,85.0,1.0,84.0,100.0,150.0,86.0,97.0,5.0,0.0,18.0,104,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2370391,6385,69.0,159.3,62.3,24.6,2.0,1,0,15.2,239.0,114.0,28.7,144.0,4.0,140.0,3.7,18.0,28.0,19.0,0.84,100.0,250.0,2500.0,100,0,100,25,0.2,2.0,36.400002,43.0,55.0,94.0,108.0,0.0,58.0,83.0,118.0,106.0,100.0,12.0,0.0,11.0,20076,IOH
2370392,6385,69.0,159.3,62.3,24.6,2.0,1,0,15.2,239.0,114.0,28.7,144.0,4.0,140.0,3.7,18.0,28.0,19.0,0.84,100.0,250.0,2500.0,100,0,100,25,0.2,2.0,36.400002,43.0,55.0,94.0,108.0,0.0,58.0,83.0,118.0,105.0,100.0,12.0,0.0,11.0,20078,IOH
2370393,6385,69.0,159.3,62.3,24.6,2.0,1,0,15.2,239.0,114.0,28.7,144.0,4.0,140.0,3.7,18.0,28.0,19.0,0.84,100.0,250.0,2500.0,100,0,100,25,0.2,2.0,36.400002,43.0,55.0,94.0,108.0,0.0,58.0,83.0,118.0,106.0,100.0,12.0,0.0,11.0,20080,IOH
2370394,6385,69.0,159.3,62.3,24.6,2.0,1,0,15.2,239.0,114.0,28.7,144.0,4.0,140.0,3.7,18.0,28.0,19.0,0.84,100.0,250.0,2500.0,100,0,100,25,0.2,2.0,36.400002,43.0,55.0,94.0,108.0,0.0,58.0,83.0,118.0,106.0,100.0,12.0,0.0,11.0,20082,IOH
2370395,6385,69.0,159.3,62.3,24.6,2.0,1,0,15.2,239.0,114.0,28.7,144.0,4.0,140.0,3.7,18.0,28.0,19.0,0.84,100.0,250.0,2500.0,100,0,100,25,0.2,2.0,36.400002,43.0,55.0,94.0,108.0,0.0,58.0,83.0,118.0,105.0,98.0,12.0,0.0,11.0,20084,IOH

In [34]:
df.columns

Index(['caseid', 'age', 'height', 'weight', 'bmi', 'asa', 'preop_htn',
       'preop_dm', 'preop_hb', 'preop_plt', 'preop_pt', 'preop_aptt',
       'preop_na', 'preop_k', 'preop_gluc', 'preop_alb', 'preop_ast',
       'preop_alt', 'preop_bun', 'preop_cr', 'intraop_ebl', 'intraop_uo',
       'intraop_crystalloid', 'intraop_ppf', 'intraop_ftn', 'intraop_rocu',
       'intraop_eph', 'Primus/MAC', 'Primus/PEEP_MBAR', 'Solar8000/BT',
       'Solar8000/ETCO2', 'Solar8000/FEO2', 'Solar8000/FIO2', 'Solar8000/HR',
       'Solar8000/INCO2', 'Solar8000/NIBP_DBP', 'Solar8000/NIBP_MBP',
       'Solar8000/NIBP_SBP', 'Solar8000/PLETH_HR', 'Solar8000/PLETH_SPO2',
       'Solar8000/RR_CO2', 'Solar8000/VENT_MAWP', 'Solar8000/VENT_RR',
       'seconds', 'label'],
      dtype='object')

In [23]:
h =df.caseid[df['label']=='IOH']

In [24]:
h.nunique()

378

In [32]:
df.shape

(2370396, 45)

In [26]:
categoricals = [col for col in df.columns if df[col].dtype == 'object' or df[col].dtype == 'str' or len(df[col].unique()) < 7]

In [27]:
categoricals

['asa', 'preop_htn', 'preop_dm', 'intraop_ftn', 'label']

In [76]:
data_tableone = data.drop(['caseid'], axis=1)
tbl_label = TableOne(data_tableone, columns=list(data_tableone.columns), missing=False, groupby='label',  pval=True, htest_name=True)
pd.set_option('display.max_rows', 500)
tbl_label

                                 Grouped by label
                                          Overall                0              1              2 P-Value           Test
n                                             604               36            348            220
age, mean (SD)                        62.7 (12.1)      65.3 (12.8)    59.6 (12.4)     67.2 (9.9)  <0.001  One-way ANOVA
height, mean (SD)                     161.8 (8.7)      159.1 (8.5)    162.5 (8.6)    161.3 (8.6)   0.036  One-way ANOVA
weight, mean (SD)                     60.7 (10.9)      58.3 (12.4)    60.2 (10.9)    61.9 (10.6)   0.079  One-way ANOVA
bmi, mean (SD)                         23.1 (3.5)       22.9 (3.7)     22.8 (3.5)     23.8 (3.4)   0.004  One-way ANOVA
asa, mean (SD)                          1.8 (0.7)        0.9 (1.2)      1.7 (0.6)      2.1 (0.5)  <0.001  One-way ANOVA
preop_htn, n (%)               0       373 (61.8)        25 (69.4)    348 (100.0)                 <0.001    Chi-squared
                               1       231 (38.2)        11 (30.6)                   220 (100.0)
preop_dm, n (%)                0       518 (85.8)        31 (86.1)     311 (89.4)     176 (80.0)   0.008    Chi-squared
                               1        86 (14.2)         5 (13.9)      37 (10.6)      44 (20.0)
preop_hb, mean (SD)                    12.0 (2.9)        6.7 (6.5)     12.4 (2.1)     12.3 (2.2)  <0.001  One-way ANOVA
preop_plt, mean (SD)                 257.2 (92.9)    179.6 (143.7)   262.6 (84.3)   261.4 (90.2)  <0.001  One-way ANOVA
preop_pt, mean (SD)                   98.0 (22.0)      61.8 (49.5)    99.3 (17.0)   101.9 (15.6)  <0.001  One-way ANOVA
preop_aptt, mean (SD)                  31.7 (7.7)      19.7 (17.0)     32.3 (5.2)     32.8 (6.8)  <0.001  One-way ANOVA
preop_na, mean (SD)                  132.1 (33.7)       -1.0 (0.0)    140.6 (2.9)    140.4 (2.7)  <0.001  One-way ANOVA
preop_k, mean (SD)                      3.8 (1.3)       -1.0 (0.0)      4.1 (0.4)      4.1 (0.4)  <0.001  One-way ANOVA
preop_gluc, mean (SD)                114.7 (48.6)      75.7 (58.0)   113.3 (43.2)   123.5 (51.8)  <0.001  One-way ANOVA
preop_alb, mean (SD)                    3.8 (0.9)        1.8 (2.4)      4.0 (0.5)      3.9 (0.6)  <0.001  One-way ANOVA
preop_ast, mean (SD)                  22.1 (13.7)      15.5 (15.6)    22.1 (13.6)    23.1 (13.4)   0.009  One-way ANOVA
preop_alt, mean (SD)                  19.1 (15.2)      11.4 (13.5)    19.4 (14.8)    19.9 (15.8)   0.007  One-way ANOVA
preop_bun, mean (SD)                   14.2 (6.8)       10.2 (9.3)     13.5 (5.0)     16.0 (8.2)  <0.001  One-way ANOVA
preop_cr, mean (SD)                     0.9 (0.9)        0.0 (0.9)      0.8 (0.5)      1.0 (1.2)  <0.001  One-way ANOVA
intraop_uo, mean (SD)               186.2 (206.5)    182.9 (197.9)  191.3 (195.1)  178.6 (225.3)   0.770  One-way ANOVA
intraop_crystalloid, mean (SD)      992.1 (909.9)  1113.0 (1125.1)  993.6 (886.1)  970.0 (911.3)   0.682  One-way ANOVA
intraop_ppf, mean (SD)                52.6 (56.3)      62.5 (56.7)    53.1 (56.7)    50.2 (55.8)   0.467  One-way ANOVA
intraop_ftn, mean (SD)                25.4 (45.9)      45.8 (57.8)    24.9 (45.6)    23.0 (43.6)   0.020  One-way ANOVA
intraop_rocu, mean (SD)               84.4 (24.1)      83.3 (30.4)    85.8 (23.3)    82.4 (24.3)   0.255  One-way ANOVA
intraop_eph, mean (SD)                10.0 (12.2)      14.3 (20.7)     9.0 (11.1)    10.8 (11.9)   0.020  One-way ANOVA

In [29]:
data_tableone = df.drop(['caseid'], axis=1)
tbl_label = TableOne(data_tableone, columns=list(data_tableone.columns),  categorical=categoricals, missing=False, groupby='label',  pval=True)
pd.set_option('display.max_rows', 500)
tbl_label

                                       Grouped by label
                                                Overall              IOH           Normal P-Value
n                                               2370396          1733617           636779
age, mean (SD)                              62.4 (12.0)      63.1 (12.3)      60.5 (11.0)  <0.001
height, mean (SD)                           162.0 (8.5)      161.3 (8.5)      164.1 (8.3)  <0.001
weight, mean (SD)                           60.5 (10.7)      59.5 (10.5)      63.3 (10.8)  <0.001
bmi, mean (SD)                               23.0 (3.4)       22.8 (3.4)       23.5 (3.5)  <0.001
asa, n (%)                      -1.0        30405 (1.3)      18984 (1.1)      11421 (1.8)  <0.001
                                1.0       641007 (27.0)    445737 (25.7)    195270 (30.7)
                                2.0      1521098 (64.2)   1160286 (66.9)    360812 (56.7)
                                3.0        170835 (7.2)     108610 (6.3)      62225 (9.8)
                                4.0          7051 (0.3)                        7051 (1.1)
preop_htn, n (%)                0        1482079 (62.5)   1078356 (62.2)    403723 (63.4)  <0.001
                                1         888317 (37.5)    655261 (37.8)    233056 (36.6)
preop_dm, n (%)                 0        2041528 (86.1)   1500333 (86.5)    541195 (85.0)  <0.001
                                1         328868 (13.9)    233284 (13.5)     95584 (15.0)
preop_hb, mean (SD)                          12.1 (2.8)       11.9 (2.7)       12.6 (2.9)  <0.001
preop_plt, mean (SD)                       259.6 (94.2)    260.6 (100.5)     256.8 (74.3)  <0.001
preop_pt, mean (SD)                         99.0 (20.1)      98.8 (20.4)      99.6 (19.5)  <0.001
preop_aptt, mean (SD)                        31.7 (6.7)       31.6 (6.4)       31.8 (7.3)  <0.001
preop_na, mean (SD)                        132.7 (32.7)     133.1 (32.0)     131.7 (34.6)  <0.001
preop_k, mean (SD)                            3.8 (1.2)        3.8 (1.2)        3.8 (1.3)  <0.001
preop_gluc, mean (SD)                      114.9 (47.5)     116.1 (49.8)     111.7 (40.3)  <0.001
preop_alb, mean (SD)                          3.9 (0.8)        3.8 (0.8)        3.9 (0.9)  <0.001
preop_ast, mean (SD)                        22.0 (13.8)      22.2 (15.0)       21.4 (9.7)  <0.001
preop_alt, mean (SD)                        19.0 (15.0)      18.6 (15.3)      20.0 (14.3)  <0.001
preop_bun, mean (SD)                         14.1 (6.4)       14.2 (6.6)       13.8 (6.0)  <0.001
preop_cr, mean (SD)                           0.8 (0.8)        0.8 (0.7)        0.9 (0.9)  <0.001
intraop_ebl, mean (SD)                    220.2 (484.2)    246.1 (552.3)    149.7 (188.6)  <0.001
intraop_uo, mean (SD)                     188.3 (215.0)    190.1 (225.4)    183.6 (183.7)  <0.001
intraop_crystalloid, mean (SD)           1001.3 (935.3)  1036.3 (1022.6)    905.9 (630.0)  <0.001
intraop_ppf, mean (SD)                      47.9 (55.8)      44.6 (54.7)      56.6 (57.7)  <0.001
intraop_ftn, n (%)              0        1717352 (72.5)   1285691 (74.2)    431661 (67.8)  <0.001
                                100       546053 (23.0)    362069 (20.9)    183984 (28.9)
                                150         11212 (0.5)       6912 (0.4)       4300 (0.7)
                                200         27186 (1.1)      19348 (1.1)       7838 (1.2)
                                50          68593 (2.9)      59597 (3.4)       8996 (1.4)
intraop_rocu, mean (SD)                     87.0 (23.9)      87.8 (24.8)      84.9 (21.1)  <0.001
intraop_eph, mean (SD)                      10.5 (12.8)      13.1 (13.5)        3.5 (6.8)  <0.001
Primus/MAC, mean (SD)                         0.4 (0.5)        0.4 (0.5)        0.5 (0.6)  <0.001
Primus/PEEP_MBAR, mean (SD)                   1.8 (2.4)        1.7 (2.4)        2.2 (2.5)  <0.001
Solar8000/BT, mean (SD)                      33.8 (5.6)       34.0 (5.3)       33.3 (6.2)  <0.001
Solar8000/ETCO2, mean (SD)                   33.4 (7.5)       33.6 (7.1)       32.8 (8.5)  <0.001
Solar8000/FEO2, mean (SD)                   38.9 (17.1)      38.4 (16.5)      40.4 (18.6)  <0.001
Solar8000/FIO2, mean (SD)                   44.3 (17.4)      43.8 (16.8)      45.7 (19.0)  <0.001
Solar8000/HR, mean (SD)                     71.2 (15.4)      71.6 (15.6)      70.2 (14.7)  <0.001
Solar8000/INCO2, mean (SD)                    1.1 (1.5)        1.1 (1.5)        1.0 (1.5)  <0.001
Solar8000/NIBP_DBP, mean (SD)               69.8 (13.1)      67.5 (12.6)      75.9 (12.5)  <0.001
Solar8000/NIBP_MBP, mean (SD)               86.0 (16.9)      83.2 (16.2)      93.6 (16.2)  <0.001
Solar8000/NIBP_SBP, mean (SD)              115.6 (23.2)     112.1 (22.3)     125.0 (22.9)  <0.001
Solar8000/PLETH_HR, mean (SD)               71.6 (15.3)      71.9 (15.3)      70.9 (15.4)  <0.001
Solar8000/PLETH_SPO2, mean (SD)              99.0 (1.9)       99.0 (2.0)       99.1 (1.8)  <0.001
Solar8000/RR_CO2, mean (SD)                  13.8 (3.4)       13.8 (3.3)       13.7 (3.7)  <0.001
Solar8000/VENT_MAWP, mean (SD)                5.6 (2.8)        5.4 (2.7)        5.8 (3.0)  <0.001
Solar8000/VENT_RR, mean (SD)                 13.8 (4.0)       13.9 (3.9)       13.7 (4.3)  <0.001
seconds, mean (SD)                      6017.0 (4655.1)  6258.2 (4828.2)  5360.2 (4075.7)  <0.001
label, n (%)                    IOH      1733617 (73.1)  1733617 (100.0)                   <0.001
                                Normal    636779 (26.9)                    636779 (100.0)

In [30]:
tbl_label.to_html('tableone.html')

In [31]:
tbl_label.to_csv('ttableone.csv')

In [65]:
data_cl1 = data.loc[data['caseid'].isin(cluster_one)]

In [67]:
tbl_one = TableOne(data_cl1, columns=list(data_cl1.columns), missing=False, htest_name=True)
pd.set_option('display.max_rows', 500)
tbl_one

                                         Overall
n                                             36
caseid, mean (SD)                2884.8 (1921.7)
age, mean (SD)                       65.3 (12.8)
height, mean (SD)                    159.1 (8.5)
weight, mean (SD)                    58.3 (12.4)
bmi, mean (SD)                        22.9 (3.7)
asa, mean (SD)                         0.9 (1.2)
preop_htn, mean (SD)                   0.3 (0.5)
preop_dm, mean (SD)                    0.1 (0.4)
preop_hb, mean (SD)                    6.7 (6.5)
preop_plt, mean (SD)               179.6 (143.7)
preop_pt, mean (SD)                  61.8 (49.5)
preop_aptt, mean (SD)                19.7 (17.0)
preop_na, mean (SD)                   -1.0 (0.0)
preop_k, mean (SD)                    -1.0 (0.0)
preop_gluc, mean (SD)                75.7 (58.0)
preop_alb, mean (SD)                   1.8 (2.4)
preop_ast, mean (SD)                 15.5 (15.6)
preop_alt, mean (SD)                 11.4 (13.5)
preop_bun, mean (SD)                  10.2 (9.3)
preop_cr, mean (SD)                    0.0 (0.9)
intraop_uo, mean (SD)              182.9 (197.9)
intraop_crystalloid, mean (SD)   1113.0 (1125.1)
intraop_ppf, mean (SD)               62.5 (56.7)
intraop_ftn, mean (SD)               45.8 (57.8)
intraop_rocu, mean (SD)              83.3 (30.4)
intraop_eph, mean (SD)               14.3 (20.7)

In [68]:
data_cl2 = data.loc[data['caseid'].isin(cluster_two)]
tbl_two = TableOne(data_cl2, columns=list(data_cl2.columns), missing=False, htest_name=True)
pd.set_option('display.max_rows', 500)
tbl_two

                                          Overall
n                                             348
caseid, mean (SD)                 3182.1 (1861.3)
age, mean (SD)                        59.6 (12.4)
height, mean (SD)                     162.5 (8.6)
weight, mean (SD)                     60.2 (10.9)
bmi, mean (SD)                         22.8 (3.5)
asa, mean (SD)                          1.7 (0.6)
preop_htn, n (%)               0      348 (100.0)
preop_dm, mean (SD)                     0.1 (0.3)
preop_hb, mean (SD)                    12.4 (2.1)
preop_plt, mean (SD)                 262.6 (84.3)
preop_pt, mean (SD)                   99.3 (17.0)
preop_aptt, mean (SD)                  32.3 (5.2)
preop_na, mean (SD)                   140.6 (2.9)
preop_k, mean (SD)                      4.1 (0.4)
preop_gluc, mean (SD)                113.3 (43.2)
preop_alb, mean (SD)                    4.0 (0.5)
preop_ast, mean (SD)                  22.1 (13.6)
preop_alt, mean (SD)                  19.4 (14.8)
preop_bun, mean (SD)                   13.5 (5.0)
preop_cr, mean (SD)                     0.8 (0.5)
intraop_uo, mean (SD)               191.3 (195.1)
intraop_crystalloid, mean (SD)      993.6 (886.1)
intraop_ppf, mean (SD)                53.1 (56.7)
intraop_ftn, mean (SD)                24.9 (45.6)
intraop_rocu, mean (SD)               85.8 (23.3)
intraop_eph, mean (SD)                 9.0 (11.1)

In [69]:
data_cl3 = data.loc[data['caseid'].isin(cluster_three)]
tbl_three = TableOne(data_cl3, columns=list(data_cl3.columns), missing=False, htest_name=True)
pd.set_option('display.max_rows', 500)
tbl_three

                                          Overall
n                                             220
caseid, mean (SD)                 3144.0 (1729.8)
age, mean (SD)                         67.2 (9.9)
height, mean (SD)                     161.3 (8.6)
weight, mean (SD)                     61.9 (10.6)
bmi, mean (SD)                         23.8 (3.4)
asa, mean (SD)                          2.1 (0.5)
preop_htn, n (%)               1      220 (100.0)
preop_dm, mean (SD)                     0.2 (0.4)
preop_hb, mean (SD)                    12.3 (2.2)
preop_plt, mean (SD)                 261.4 (90.2)
preop_pt, mean (SD)                  101.9 (15.6)
preop_aptt, mean (SD)                  32.8 (6.8)
preop_na, mean (SD)                   140.4 (2.7)
preop_k, mean (SD)                      4.1 (0.4)
preop_gluc, mean (SD)                123.5 (51.8)
preop_alb, mean (SD)                    3.9 (0.6)
preop_ast, mean (SD)                  23.1 (13.4)
preop_alt, mean (SD)                  19.9 (15.8)
preop_bun, mean (SD)                   16.0 (8.2)
preop_cr, mean (SD)                     1.0 (1.2)
intraop_uo, mean (SD)               178.6 (225.3)
intraop_crystalloid, mean (SD)      970.0 (911.3)
intraop_ppf, mean (SD)                50.2 (55.8)
intraop_ftn, mean (SD)                23.0 (43.6)
intraop_rocu, mean (SD)               82.4 (24.3)
intraop_eph, mean (SD)                10.8 (11.9)